<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>sqlzsgc</title>
    </head>
    <body>
        <?php
            //print_r($message);
            echo'<br>Number:'.$message[0].' Name:'.$message[1];
        ?>
    </body>
</html>
